/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CozumOrtagiOlRouteImport } from './routes/cozum-ortagi-ol'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as MerkezlerRouteImport } from './routes/merkezler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CozumOrtagiOlRoute = CozumOrtagiOlRouteImport.update({
  id: '/cozum-ortagi-ol',
  path: '/cozum-ortagi-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const MerkezlerRoute = MerkezlerRouteImport.update({
  id: '/merkezler',
  path: '/merkezler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cozum-ortagi-ol': typeof CozumOrtagiOlRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/merkezler': typeof MerkezlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cozum-ortagi-ol': typeof CozumOrtagiOlRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/merkezler': typeof MerkezlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cozum-ortagi-ol': typeof CozumOrtagiOlRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/merkezler': typeof MerkezlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cozum-ortagi-ol' | '/hakkimizda' | '/iletisim' | '/merkezler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cozum-ortagi-ol' | '/hakkimizda' | '/iletisim' | '/merkezler'
  id:
    | '__root__'
    | '/'
    | '/cozum-ortagi-ol'
    | '/hakkimizda'
    | '/iletisim'
    | '/merkezler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CozumOrtagiOlRoute: typeof CozumOrtagiOlRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  MerkezlerRoute: typeof MerkezlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozum-ortagi-ol': {
      id: '/cozum-ortagi-ol'
      path: '/cozum-ortagi-ol'
      fullPath: '/cozum-ortagi-ol'
      preLoaderRoute: typeof CozumOrtagiOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merkezler': {
      id: '/merkezler'
      path: '/merkezler'
      fullPath: '/merkezler'
      preLoaderRoute: typeof MerkezlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CozumOrtagiOlRoute: CozumOrtagiOlRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  MerkezlerRoute: MerkezlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
